<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Membership_model extends CI_Model
{

    public $table = 'membership';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('first_name', $q);
	$this->db->or_like('last_name', $q);
	$this->db->or_like('email_addres', $q);
	$this->db->or_like('user_name', $q);
	$this->db->or_like('pass_word', $q);
	$this->db->or_like('group', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('first_name', $q);
	$this->db->or_like('last_name', $q);
	$this->db->or_like('email_addres', $q);
	$this->db->or_like('user_name', $q);
	$this->db->or_like('pass_word', $q);
	$this->db->or_like('group', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function get_user($user_name){
        $this->db->select('*');
        $this->db->from('membership');
        $this->db->where('user_name', $user_name);
        $this->db->limit(1);
        $query = $this->db->get();
        return $query->result_array(); 
    }

}

/* End of file Membership_model.php */
/* Location: ./application/models/Membership_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-07-02 19:30:27 */
/* http://harviacode.com */