<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Assignments_model extends CI_Model
{

    public $table = 'assignments';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL, $assignmented_for_person_id = NULL) {
        $this->db->like('id', $q);
        $this->db->or_like('asset_id', $q);
        $this->db->or_like('created_by_person_id', $q);
        $this->db->or_like('assignmented_for_person_id', $q);
        $this->db->or_like('cost_center_id', $q);
        $this->db->or_like('status_id', $q);
        $this->db->or_like('created_at', $q);
        $this->db->or_like('updated_at', $q);
        $this->db->or_like('deleted_at', $q);
        $this->db->or_like('origin_location_id', $q);
        $this->db->or_like('destiny_location_id', $q);
        $this->db->or_like('reason_id', $q);
        $this->db->or_like('item_id', $q);
        $this->db->or_like('scheduled_at', $q);
        $this->db->or_like('comments', $q);
        if (!is_null($assignmented_for_person_id)){
            $this->db->where('assignmented_for_person_id', $assignmented_for_person_id);
            $this->db->or_where('assignmented_for_person_id', '0');
        }
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL, $assignmented_for_person_id = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('asset_id', $q);
        $this->db->or_like('created_by_person_id', $q);
        $this->db->or_like('assignmented_for_person_id', $q);
        $this->db->or_like('cost_center_id', $q);
        $this->db->or_like('status_id', $q);
        $this->db->or_like('created_at', $q);
        $this->db->or_like('updated_at', $q);
        $this->db->or_like('deleted_at', $q);
        $this->db->or_like('origin_location_id', $q);
        $this->db->or_like('destiny_location_id', $q);
        $this->db->or_like('reason_id', $q);
        $this->db->or_like('item_id', $q);
        $this->db->or_like('scheduled_at', $q);
        $this->db->or_like('comments', $q);
        if (!is_null($assignmented_for_person_id)){
            $this->db->where('assignmented_for_person_id', $assignmented_for_person_id);
            $this->db->or_where('assignmented_for_person_id', '0');
        }

        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Assignments_model.php */
/* Location: ./application/models/Assignments_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-07-02 16:54:23 */
/* http://harviacode.com */