<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Utils_model extends CI_Model
{

    function __construct()
    {
        parent::__construct();
    }


    function get_all_reasons()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('reasons')->result();
    }

    function get_reason_by_id($id)
    {
        $this->db->where('id', $id);
        return $this->db->get('reasons')->row();
    }

    function get_all_assignment_status()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('assignment_status')->result();
    }

    function get_assignment_status_by_id($id)
    {
        $this->db->where('id', $id);
        return $this->db->get('assignment_status')->row();
    }

}

/* End of file Items_model.php */
/* Location: ./application/models/Items_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-06-25 22:27:05 */
/* http://harviacode.com */