<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Assignment_statu extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Assignment_statu_model');
    }
}
