<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Location extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Location_model');
    } 

    /*
     * Listing of locations
     */
    function index()
    {
        $data['locations'] = $this->Location_model->get_all_locations();
        
        $data['_view'] = 'location/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new location
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'cost_center_id' => $this->input->post('cost_center_id'),
				'floor' => $this->input->post('floor'),
				'block' => $this->input->post('block'),
				'sector' => $this->input->post('sector'),
				'room' => $this->input->post('room'),
				'created_at' => $this->input->post('created_at'),
				'updated_at' => $this->input->post('updated_at'),
				'deleted_at' => $this->input->post('deleted_at'),
				'status' => $this->input->post('status'),
				'fone' => $this->input->post('fone'),
				'location_type' => $this->input->post('location_type'),
            );
            
            $location_id = $this->Location_model->add_location($params);
            redirect('location/index');
        }
        else
        {
			$this->load->model('Cost_center_model');
			$data['all_cost_centers'] = $this->Cost_center_model->get_all_cost_centers();
            
            $data['_view'] = 'location/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a location
     */
    function edit($id)
    {   
        // check if the location exists before trying to edit it
        $data['location'] = $this->Location_model->get_location($id);
        
        if(isset($data['location']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'cost_center_id' => $this->input->post('cost_center_id'),
					'floor' => $this->input->post('floor'),
					'block' => $this->input->post('block'),
					'sector' => $this->input->post('sector'),
					'room' => $this->input->post('room'),
					'created_at' => $this->input->post('created_at'),
					'updated_at' => $this->input->post('updated_at'),
					'deleted_at' => $this->input->post('deleted_at'),
					'status' => $this->input->post('status'),
					'fone' => $this->input->post('fone'),
					'location_type' => $this->input->post('location_type'),
                );

                $this->Location_model->update_location($id,$params);            
                redirect('location/index');
            }
            else
            {
				$this->load->model('Cost_center_model');
				$data['all_cost_centers'] = $this->Cost_center_model->get_all_cost_centers();

                $data['_view'] = 'location/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The location you are trying to edit does not exist.');
    } 

    /*
     * Deleting location
     */
    function remove($id)
    {
        $location = $this->Location_model->get_location($id);

        // check if the location exists before trying to delete it
        if(isset($location['id']))
        {
            $this->Location_model->delete_location($id);
            redirect('location/index');
        }
        else
            show_error('The location you are trying to delete does not exist.');
    }
    
}
