<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Membership extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Membership_model');
    } 

    /*
     * Listing of membership
     */
    function index()
    {
        $data['membership'] = $this->Membership_model->get_all_membership();
        
        $data['_view'] = 'membership/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new membership
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'first_name' => $this->input->post('first_name'),
				'last_name' => $this->input->post('last_name'),
				'email_addres' => $this->input->post('email_addres'),
				'user_name' => $this->input->post('user_name'),
				'pass_word' => $this->input->post('pass_word'),
				'group' => $this->input->post('group'),
            );
            
            $membership_id = $this->Membership_model->add_membership($params);
            redirect('membership/index');
        }
        else
        {            
            $data['_view'] = 'membership/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a membership
     */
    function edit($id)
    {   
        // check if the membership exists before trying to edit it
        $data['membership'] = $this->Membership_model->get_membership($id);
        
        if(isset($data['membership']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'first_name' => $this->input->post('first_name'),
					'last_name' => $this->input->post('last_name'),
					'email_addres' => $this->input->post('email_addres'),
					'user_name' => $this->input->post('user_name'),
					'pass_word' => $this->input->post('pass_word'),
					'group' => $this->input->post('group'),
                );

                $this->Membership_model->update_membership($id,$params);            
                redirect('membership/index');
            }
            else
            {
                $data['_view'] = 'membership/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The membership you are trying to edit does not exist.');
    } 

    /*
     * Deleting membership
     */
    function remove($id)
    {
        $membership = $this->Membership_model->get_membership($id);

        // check if the membership exists before trying to delete it
        if(isset($membership['id']))
        {
            $this->Membership_model->delete_membership($id);
            redirect('membership/index');
        }
        else
            show_error('The membership you are trying to delete does not exist.');
    }
    
}
