<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Assignment_statu extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Assignment_statu_model');
    } 

    /*
     * Listing of assignment_status
     */
    function index()
    {
        $data['assignment_status'] = $this->Assignment_statu_model->get_all_assignment_status();
        
        $data['_view'] = 'assignment_statu/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new assignment_statu
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'name' => $this->input->post('name'),
				'description' => $this->input->post('description'),
				'created_at' => $this->input->post('created_at'),
				'updated_at' => $this->input->post('updated_at'),
				'deleted_at' => $this->input->post('deleted_at'),
            );
            
            $assignment_statu_id = $this->Assignment_statu_model->add_assignment_statu($params);
            redirect('assignment_statu/index');
        }
        else
        {            
            $data['_view'] = 'assignment_statu/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a assignment_statu
     */
    function edit($id)
    {   
        // check if the assignment_statu exists before trying to edit it
        $data['assignment_statu'] = $this->Assignment_statu_model->get_assignment_statu($id);
        
        if(isset($data['assignment_statu']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'name' => $this->input->post('name'),
					'description' => $this->input->post('description'),
					'created_at' => $this->input->post('created_at'),
					'updated_at' => $this->input->post('updated_at'),
					'deleted_at' => $this->input->post('deleted_at'),
                );

                $this->Assignment_statu_model->update_assignment_statu($id,$params);            
                redirect('assignment_statu/index');
            }
            else
            {
                $data['_view'] = 'assignment_statu/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The assignment_statu you are trying to edit does not exist.');
    } 

    /*
     * Deleting assignment_statu
     */
    function remove($id)
    {
        $assignment_statu = $this->Assignment_statu_model->get_assignment_statu($id);

        // check if the assignment_statu exists before trying to delete it
        if(isset($assignment_statu['id']))
        {
            $this->Assignment_statu_model->delete_assignment_statu($id);
            redirect('assignment_statu/index');
        }
        else
            show_error('The assignment_statu you are trying to delete does not exist.');
    }
    
}
