<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Reason extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Reason_model');
    } 

    /*
     * Listing of reasons
     */
    function index()
    {
        $data['reasons'] = $this->Reason_model->get_all_reasons();
        
        $data['_view'] = 'reason/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new reason
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'name' => $this->input->post('name'),
				'description' => $this->input->post('description'),
				'created_at' => $this->input->post('created_at'),
				'updated_at' => $this->input->post('updated_at'),
				'deleted_at' => $this->input->post('deleted_at'),
            );
            
            $reason_id = $this->Reason_model->add_reason($params);
            redirect('reason/index');
        }
        else
        {            
            $data['_view'] = 'reason/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a reason
     */
    function edit($id)
    {   
        // check if the reason exists before trying to edit it
        $data['reason'] = $this->Reason_model->get_reason($id);
        
        if(isset($data['reason']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'name' => $this->input->post('name'),
					'description' => $this->input->post('description'),
					'created_at' => $this->input->post('created_at'),
					'updated_at' => $this->input->post('updated_at'),
					'deleted_at' => $this->input->post('deleted_at'),
                );

                $this->Reason_model->update_reason($id,$params);            
                redirect('reason/index');
            }
            else
            {
                $data['_view'] = 'reason/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The reason you are trying to edit does not exist.');
    } 

    /*
     * Deleting reason
     */
    function remove($id)
    {
        $reason = $this->Reason_model->get_reason($id);

        // check if the reason exists before trying to delete it
        if(isset($reason['id']))
        {
            $this->Reason_model->delete_reason($id);
            redirect('reason/index');
        }
        else
            show_error('The reason you are trying to delete does not exist.');
    }
    
}
