<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cost_center_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get cost_center by id
     */
    function get_cost_center($id)
    {
        return $this->db->get_where('cost_centers',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all cost_centers
     */
    function get_all_cost_centers()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('cost_centers')->result_array();
    }
        
    /*
     * function to add new cost_center
     */
    function add_cost_center($params)
    {
        $this->db->insert('cost_centers',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update cost_center
     */
    function update_cost_center($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('cost_centers',$params);
    }
    
    /*
     * function to delete cost_center
     */
    function delete_cost_center($id)
    {
        return $this->db->delete('cost_centers',array('id'=>$id));
    }
}
