<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Membership_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get membership by id
     */
    function get_membership($id)
    {
        return $this->db->get_where('membership',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all membership
     */
    function get_all_membership()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('membership')->result_array();
    }
        
    /*
     * function to add new membership
     */
    function add_membership($params)
    {
        $this->db->insert('membership',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update membership
     */
    function update_membership($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('membership',$params);
    }
    
    /*
     * function to delete membership
     */
    function delete_membership($id)
    {
        return $this->db->delete('membership',array('id'=>$id));
    }
}
