<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Asset_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get asset by id
     */
    function get_asset($id)
    {
        return $this->db->get_where('assets',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all assets count
     */
    function get_all_assets_count()
    {
        $this->db->from('assets');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all assets
     */
    function get_all_assets($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('assets')->result_array();
    }
        
    /*
     * function to add new asset
     */
    function add_asset($params)
    {
        $this->db->insert('assets',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update asset
     */
    function update_asset($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('assets',$params);
    }
    
    /*
     * function to delete asset
     */
    function delete_asset($id)
    {
        return $this->db->delete('assets',array('id'=>$id));
    }
}
